accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='main'),
]

arsip/urls.py
from django.urls import path
from . import views

app_name = 'arsip'

urlpatterns = [
    path('', views.arsip_list, name='arsip-list'),
    path('buat-arsip/', views.create_arsip_view, name='arsip-register'),
    path('arsip-detail/<id>/', views.arsip_detail, name='arsip-detail'),
    path('arsip/<int:id>/request-tarik/', views.request_tarik, name='request-tarik'),
    path('arsip/<int:id>/request-ganti/', views.request_ganti, name='request-ganti'),
    path('arsip/<int:id>/posting', views.approve_request, name='posting-arsip'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from main import views as core_views

handler403 = core_views.custom_permission_denied_view
handler404 = core_views.custom_page_not_found_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('main.urls')),
    path('arsip/', include('arsip.urls'), name='arsip'),
    path('403/', core_views.custom_permission_denied_view),
    path('404/', core_views.custom_page_not_found_view),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # THIS MATTER THE MOST TO MAKE UPLOAD HAPPENS!!!

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('dashboard/', views.dashboard_view, name='dashboard'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render

from accounts.views import is_staff

@login_required
@user_passes_test(is_staff)
def dashboard_view(request):
    return render(request, 'main/dashboard.html')

def custom_permission_denied_view(request, exception=None):
    return render(request, 'main/403.html', status=403)

def custom_page_not_found_view(request, exception=None):
    return render(request, 'main/404.html', status=404)

main/templates/main/base.html
{% load static %}
{% load icon %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>PANCA LOGAM INTRANET</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>


</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script> -->
<script src="{% static 'js/dashboard.js' %}"></script>


<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">PANCA LOGAM</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <a class="nav-link px-3" href="{% url 'accounts:logout' %}">Sign out</a>
    </div>
  </div>
</header>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="position-sticky pt-3">
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active {% endif %}" aria-current="page" href="{% url 'main:dashboard' %}">
              <span>{% icon "home" class="css-class" height="18" width="18" %}</span>
              Dashboard
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path|slice:':7' == '/arsip/' %}active{% endif %}"
                href="{% url 'arsip:arsip-list' %}">
              <span>{% icon "file" class="css-class" height="18" width="18" %}</span>
              Arsip
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li> -->
        </ul>

        <!-- <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Saved reports</span>
          <a class="link-secondary" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Current month
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li>
        </ul> -->
      </div>
    </nav>

    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
{#      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">#}
{#        <h1 class="h2">Dashboard</h1>#}
{#        <div class="btn-toolbar mb-2 mb-md-0">#}
{#          <div class="btn-group me-2">#}
{#            <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>#}
{#            <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>#}
{#          </div>#}
{#          <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">#}
{#            <span data-feather="calendar"></span>#}
{#            This week#}
{#          </button>#}
{#        </div>#}
{#      </div>#}
      {% block content %}
      <!-- Disini Kontent goes -->
      {% endblock %}
    </main>
  </div>
{#      <canvas class="my-4 w-100" id="myChart" width="900" height="380"></canvas>#}

{#      <h2>Section title</h2>#}
{#        This is where#}

{#    <nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#    <div class="container-fluid">#}
{#        <a class="navbar-brand" href="#">Panca Logam Intranet</a>#}
{#        <div class="collapse navbar-collapse">#}
{#            <ul class="navbar-nav me-auto mb-2 mb-lg-0">#}
{#                {% if user.is_authenticated %}#}
{#                    {% if user.role == 'admin' %}#}
{#                        <li class="nav-item"><a class="nav-link" href="/admin-dashboard/">Admin Dashboard</a></li>#}
{#                        <li class="nav-item"><a class="nav-link" href="/admin/">Admin Panel</a></li>#}
{#                    {% elif user.role == 'staff' %}#}
{#                        <li class="nav-item"><a class="nav-link" href="/user-dashboard/">Dashboard</a></li>#}
{#                    {% endif %}#}
{#                    <li class="nav-item"><a class="nav-link" href="/logout/">Logout</a></li>#}
{#                {% else %}#}
{#                    <li class="nav-item"><a class="nav-link" href="/login/">Login</a></li>#}
{#                    <li class="nav-item"><a class="nav-link" href="/register/">Register</a></li>#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </div>#}
{#</nav>#}
{#<div class="container-mt-4">#}
{#    {% block content %}#}
{#    {% endblock %}#}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- {#</div>#} -->
</div>
{% block extra_js %}{% endblock %}
</body>
</html>

main/templates/main/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Remember me
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign in</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
  </form>
</main>


    
  </body>
</html>

main/templates/main/jumb.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Jumbotron example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/jumbotron/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    
<main>
  <div class="container py-4">
    <header class="pb-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg>
        <span class="fs-4">Jumbotron example</span>
      </a>
    </header>

    <div class="p-5 mb-4 bg-light rounded-3">
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Custom jumbotron</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <button class="btn btn-primary btn-lg" type="button">Example button</button>
      </div>
    </div>

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

    <footer class="pt-3 mt-4 text-muted border-top">
      &copy; 2021
    </footer>
  </div>
</main>


    
  </body>
</html>

main/templates/main/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.84.0">
    <title>Signin Template · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

    

    <!-- Bootstrap core CSS -->
<link href="../assets/dist/css/bootstrap.min.css" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
    <!-- Custom styles for this template -->
    <link href="signin.css" rel="stylesheet">
  </head>
  <body class="text-center">
    
<main class="form-signin">
  <form>
    <img class="mb-4" src="../assets/brand/bootstrap-logo.svg" alt="" width="72" height="57">
    <h1 class="h3 mb-3 fw-normal">Please sign in</h1>

    <div class="form-floating">
      <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Email address</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
      <label for="floatingPassword">Password</label>
    </div>

    <div class="checkbox mb-3">
      <label>
        <input type="checkbox" value="remember-me"> Ingat Saya
      </label>
    </div>
    <button class="w-100 btn btn-lg btn-primary" type="submit">Masuk</button>
    <p class="mt-5 mb-3 text-muted">&copy; 2025</p>
  </form>
</main>


    
  </body>
</html>

main/templates/main/main.html
{% extends 'main/base.html' %}
{% load static %}
{% block head_extra %}
     <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
{% endblock %}
{% block content %}
    <head>
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
    </head>
    <main>
    <header class="pb-2 pt-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
        <span class="fs-4">Pending Job - Daftar Nota Titipan </span>
      </a>
    </header>

    <div class="pending-card">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Nama Pembeli</th>
            <th scope="col">Tanggal Nota</th>
            <th scope="col">Barang Sudah Diambil?</th>
            <th scope="col">Status Posting</th>
            <th scope="col">Detail</th>
          </tr>
        </thead>
        <tbody>
          {% for arsip in arsip_page %}
              <tr>
                  <td>{{ forloop.counter }}</td>
                  <td>{{ arsip.nota_cust_name }}</td>
                  <td>{{ arsip.nota_date }}</td>
                  <td>{% if arsip.nota_sudah_diambil == 1 %}
                      <span class="badge rounded-pill text-bg-danger">Barang Sudah Diambil</span>
                      {% else %}
                      <span class="badge rounded-pill text-bg-success">Belum Diambil</span>
                      {% endif %}
                  </td>
                  <td>
                    {% if arsip.nota_status == "unposted" %}
                      <span class="badge text-bg-primary">Belum diposting</span>
                    {% elif arsip.nota_status == "req_tarik_nota" %}
                      <span class="badge text-bg-warning">Proses Posting</span>
                    {% elif arsip.nota_status == "req_ganti_nota" %}
                      <span class="badge text-bg-warning">Proses Posting</span>
                    {% elif arsip.nota_status == "req_retur_nota" %}
                      <span class="badge text-bg-warning">Proses Posting</span>
                    {% elif arsip.nota_status == "posted" %}
                      <span class="badge text-bg-warning">Sudah Posting</span>
                    {% else %}
                      <span class="badge text-bg-info">N/A</span>
                    {% endif %}
                  </td>
                  <td><a class="btn btn-secondary" href="{% url 'arsip:arsip-detail' arsip.id %}">Lihat</a></td>
              </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    

    <div class="row align-items-md-stretch">
      <div class="col-md-6">
        <div class="h-100 p-5 text-white bg-dark rounded-3">
          <h2>Change the background</h2>
          <p>Swap the background-color utility and add a `.text-*` color utility to mix up the jumbotron look. Then, mix and match with additional component themes and more.</p>
          <button class="btn btn-outline-light" type="button">Example button</button>
        </div>
      </div>
      <div class="col-md-6">
        <div class="h-100 p-5 bg-light border rounded-3">
          <h2>Add borders</h2>
          <p>Or, keep it light and add a border for some added definition to the boundaries of your content. Be sure to look under the hood at the source HTML here as we've adjusted the alignment and sizing of both column's content for equal-height.</p>
          <button class="btn btn-outline-secondary" type="button">Example button</button>
        </div>
      </div>
    </div>

</main>
{% endblock %}